services:
    _defaults:
        autowire: true
        autoconfigure: true

    Rallo\ContaoTheme\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Resources/'
            - '../src/RctBundle.php'

    Rallo\ContaoTheme\DCA\RctFontOptionsCallback:
        public: true

    Rallo\ContaoTheme\DCA\IconPickerWizard:
        public: true
